services:
  wis:
    restart: unless-stopped
    image: ${IMAGE}:${TAG}
    env_file:
      - .env
    shm_size: ${SHM_SIZE}
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    #build:
    #  dockerfile: Dockerfile
    ports:
      - ${LISTEN_IP}:${MEDIA_PORT_RANGE}:${MEDIA_PORT_RANGE}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ['0']
    volumes:
      - ./:/app
      - ./cache:/root/.cache
    command: ./entrypoint.sh

  coqui:
    restart: unless-stopped
    image: ${COQUI_IMAGE}:${COQUI_TAG}
    env_file:
      - .env
    shm_size: ${SHM_SIZE}
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ['0']
    volumes:
      - ./:/app
      - ./cache:/root/.cache
      - ./cache-local:/root/.local
    entrypoint: /app/entrypoint-coqui.sh

  nginx:
    restart: unless-stopped
    depends_on:
      - coqui
      - wis
    image: ${WIS_NGINX_IMAGE}:${WIS_NGINX_TAG}
    volumes:
    - ./nginx:/nginx
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #environment:
    #  - NGINX_ENTRYPOINT_WORKER_PROCESSES_AUTOTUNE=1
    ports:
    - ${LISTEN_IP}:${LISTEN_PORT_HTTPS}:19000
    - ${LISTEN_IP}:${LISTEN_PORT}:19001